### PR TITLE
don't clean active pipelines

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26)

### CODE REVIEW

**Review by nassiharel — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26)* status: all files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[dockerfile/Dockerfile, line 3 at r1](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26#-MuKT0WPDuRRNUOL2dnK:-MuKT0WPDuRRNUOL2dnL:bfq2zco) ([raw file](https://github.com/kube-hpc/etcd-cleaner/blob/8dfe45b7518387ba73af9c4305bb040a0354ed57/dockerfile/Dockerfile#L3)):*
> ```Dockerfile
> ARG BASE_PRIVATE_REGISTRY=""
> FROM ${BASE_PRIVATE_REGISTRY}node:14.5.0 as install
> ADD ./package-lock.json ./package.json /hkube/etcd-cleaner/
> ```

You can do 
```
ADD ./package*.json /hkube/etcd-cleaner/
```

No?



_Code quote:_
```Dockerfile
ADD ./package-lock.json ./package.json /hkube/etcd-cleaner/
```
___
*[lib/cleaners/etcd.js, line 28 at r1](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26#-MuKUdlwDtBl3EbsVH7s:-MuKUdlwDtBl3EbsVH7t:bg4hkci) ([raw file](https://github.com/kube-hpc/etcd-cleaner/blob/8dfe45b7518387ba73af9c4305bb040a0354ed57/lib/cleaners/etcd.js#L28)):*
> ```JavaScript
>     const promises = [];
>     const count = Object.create(null);
>     const statusesRaw = await etcdStore.getKeys('/jobs/status');
> ```

This could not lead to OOM?
Don't you want to clean the entire etcd data? (like in the gc-service)



_Code quote:_
```JavaScript
 const statusesRaw = await etcdStore.getKeys('/jobs/status');
```

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[dockerfile/Dockerfile, line 3 at r1](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26#-MuKT0WPDuRRNUOL2dnK:-MuLIjPp7oNxVgbZt_bI:bogcq83) ([raw file](https://github.com/kube-hpc/etcd-cleaner/blob/8dfe45b7518387ba73af9c4305bb040a0354ed57/dockerfile/Dockerfile#L3)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

You can do 
```
ADD ./package*.json /hkube/etcd-cleaner/
```

No?
</blockquote></details>

Maybe, but I want to be specific here
___
*[lib/cleaners/etcd.js, line 28 at r1](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26#-MuKUdlwDtBl3EbsVH7s:-MuQ6VVn58MBn8kNhrV9:bpvymws) ([raw file](https://github.com/kube-hpc/etcd-cleaner/blob/8dfe45b7518387ba73af9c4305bb040a0354ed57/lib/cleaners/etcd.js#L28)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

This could not lead to OOM?
Don't you want to clean the entire etcd data? (like in the gc-service)
</blockquote></details>

made some changes - not getting all together, but each path on it's own. less chance of OOM.

**Review by nassiharel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26)* status: 9 of 10 files reviewed, 2 unresolved

**Review by nassiharel — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

**Review by nassiharel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[lib/cleaners/etcd.js, line 36 at r2](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26#-MuR0aef9OpVCGs2y2v8:-MuR0aef9OpVCGs2y2v9:b-lvvhhu) ([raw file](https://github.com/kube-hpc/etcd-cleaner/blob/06706a691c81b6224c54d9bfd1862a9b92be3fc3/lib/cleaners/etcd.js#L36)):*
> ```JavaScript
>     }, {});
> 
>     for (const path of [...paths, statusPath]) {
> ```

Isn't this code fetching the `/jobs/status` twice?



_Code quote:_
```JavaScript
/jobs/status
```

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[lib/cleaners/etcd.js, line 29 at r2](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26#-MuR-WvVCaFIqczVJH3V:-MuR3EaL4vVA5En03NsD:b8evd0r) ([raw file](https://github.com/kube-hpc/etcd-cleaner/blob/06706a691c81b6224c54d9bfd1862a9b92be3fc3/lib/cleaners/etcd.js#L29)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I think that this line can lead to OOM, since you are fetching 10,000 objects
</blockquote></details>

I know, but I don't want to do a major change like in gc-cleaner on this branch. Here we can give it more memory
Besides, I think that the ETCD will choke first. That's why I separated it by path
___
*[lib/cleaners/etcd.js, line 36 at r2](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26#-MuR0aef9OpVCGs2y2v8:-MuR38tZ2M2kv2abIdyC:bb6un1j) ([raw file](https://github.com/kube-hpc/etcd-cleaner/blob/06706a691c81b6224c54d9bfd1862a9b92be3fc3/lib/cleaners/etcd.js#L36)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Isn't this code fetching the `/jobs/status` twice
</blockquote></details>

Done

**Review by nassiharel — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[lib/cleaners/etcd.js, line 19 at r3](https://reviewable.io/reviews/kube-hpc/etcd-cleaner/26#-MuR4BIBAP5e3qevd9SK:-MuR4BIBAP5e3qevd9SL:b-oizank) ([raw file](https://github.com/kube-hpc/etcd-cleaner/blob/f71f57c725b738a91ca7c855348f3fd109b58fb0/lib/cleaners/etcd.js#L19)):*
> ```JavaScript
>     '/workers',
>     '/drivers',
>     '/executions',
> ```

This is the path that can lead to OOM (flowInput)
Don't forget to increase memory...



_Code quote:_
```JavaScript
'/executions'
```

**Pull request merged**
